title: Olavo Mendes
logo: "/images/perfil.png?raw=true"
description: >
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/olavo-mendes/">Meu LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
