title: Olavo Mendes
logo: "/images/perfil.png?raw=true"
description: >
  <p align="justify">
    Sou graduando em Sistemas de Informação pela Universidade Federal
    do Ceará - UFC. Me procure se quiser falar sobre <b>Data Science</b>,
    <b>Machine Learning</b>, <b>Deep Learning</b> ou <b>Arduino</b>.
  </p>
  <br>
  <a href="https://www.linkedin.com/in/olavo-mendes/">Meu LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
