title: <center> Olavo Mendes </center>
logo: "/images/perfil.png?raw=true"
description: >
  <p align="justify">
    Desenvolvedor Backend que lê Asimov e PKD mais do que deveria.
    Me procure se quiser falar sobre <b>NodeJs</b>, <b>Machine Learning</b>, <b>Deep Learning</b>, <b>Eletrônica</b>, <b>Arduino</b>, <b>Asimov</b>, <b>PKD</b> e/ou <b>Mass Effect</b>.
  </p>
  <a href="https://www.linkedin.com/in/olavo-mendes/">LinkedIn</a> 
  <p></p>
  <a href="https://www.kaggle.com/olavomendes">Kaggle</a> 
  
theme: jekyll-theme-minimal
